[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
# Comme CORS est désactivé, nous désactivons aussi la protection XSRF
# pour éviter les conflits
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20

[browser]
gatherUsageStats = false
