[connections.snowflake]
account = "VQGXAPG-NAB96986"
user = "agiraud"
private_key_file = "C:/Users/Antoine.Giraud/.ssh/perso/key_agiraud_snowflake"
role = "BIKESHARE_LOADER"
warehouse = "BIKESHARE_LOADING_WH"
database = "BIKESHARE"
schema = "BRONZE"
