[connections.snowflake]
account = "xxxxx-xxxxx"
user = "agiraud"
private_key_file = "~/.ssh/my_snowflake_key"
role = "BIKESHARE_LOADER"
warehouse = "BIKESHARE_LOADING_WH"
database = "BIKESHARE"
schema = "BRONZE"
